name: Minikube (manusa/actions-setup-minikube)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Manifests
        run: |
          kubectl apply -f manifests/whalesay.yaml
          kubectl apply -f manifests/redis.yaml
          sleep 30

      - name: Dump Kubernetes Logs
        run: |
          ./kubelogs.sh -n kube-system -o output-minikube-manusa --timestamps true
          ./kubelogs.sh -n default -o output-minikube-manusa --timestamps true

      - name: Log File Sizes
        run: |
          ls -lhR output-minikube-manusa

      - name: Generate Filetree
        run: |
          yarn install
          yarn script index.ts

      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()

#           - name: Setup node
#   uses: actions/setup-node@v3
#   with:
#     node-version: '16'
# - name: Setup cache
#   uses: actions/cache@v3
#   with:
#     path: |
#       ${{ github.workspace }}/action/node_modules
#       ${{ github.workspace }}/cli/node_modules
#     key: ${{ runner.os }}-node-16-cli-${{ hashFiles('cli/yarn.lock') }}-${{ hashFiles('action/yarn.lock') }}
# - name: Install action dependencies
#   run: |
#     yarn install --frozen-lockfile

